apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: file-entry-storage-binding
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
    - name: storageAccount
      value: [Account Name]
    - name: storageAccessKey
      value: [Account key]
    - name: container
      value: file-entry
    - name: decodeBase64
      value: true